version: '3.8'
services:
  inventory-service:
    build: ./inventory-service
    ports:
      - "8081:8081"
  shipment-service:
    build: ./shipment-service
    ports:
      - "8082:8082"
  notification-service:
    build: ./notification-service
    ports:
      - "8083:8083"
  worker-service:
    build: ./worker-service
    ports:
      - "8084:8084"
  
  # Local DynamoDB for development/testing
  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"

  # LocalStack for local AWS SQS and SNS emulation
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,sns